export const crewList = {
  cc_event_id: 201606,
  name: "VR 2025",
  description: "Velikonoční regata",
  status_text: "running",
  race_type: "offshore",
  eventtype_text: "boat_race",
  event_end: "2025-04-05T12:00:00+02:00",
  event_start: "2025-03-29T12:00:00+01:00",
  slug: "vr-2025",
  active: true,
  default_lat: 43.826,
  default_lng: 15.5869,
  cc_object: [
    {
      id: 201502609,
      name: "Pavlíček",
      start_number: 1,
      description: "Martin Pavlíček - Sebranka - MIMAS",
      track_color: "#392abf",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502610,
      name: "Jakubec",
      start_number: 2,
      description: "Pavel Jakubec - Dušín Czech Sailing team - MH52",
      track_color: "#daa520",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502611,
      name: "Bělohoubek",
      start_number: 3,
      description: "Jaroslav Bělohoubek - Jachting4FUN - MH49",
      track_color: "#1b6b0a",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502612,
      name: "Kelemen",
      start_number: 4,
      description: "Michal Kelemen - Kolotočári - MH79",
      track_color: "#32a0fa",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502613,
      name: "Vaidiš",
      start_number: 5,
      description: "Tomáš Vaidiš - ERIS",
      track_color: "#f75e61",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502614,
      name: "Knop-Kostka",
      start_number: 6,
      description: "David Knop-Kostka - MH54",
      track_color: "#e377c3",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502615,
      name: "Gřundil",
      start_number: 7,
      description: "David Gřundil - NEVYMĚKNEM! - MH77",
      track_color: "#ba4a7b",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502616,
      name: "Zloch",
      start_number: 8,
      description: "Petr Zloch - NaBLB sailing team - NABU",
      track_color: "#4f4f22",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502617,
      name: "Princová",
      start_number: 9,
      description: "Lea Princová - Chiquitas - MH53",
      track_color: "#32678a",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502618,
      name: "Mach",
      start_number: 10,
      description: "Jiří Mach - SDJ Orange Yacht - TITAN",
      track_color: "#daa520",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502619,
      name: "Kuchyňka",
      start_number: 11,
      description: "Vojtěch Kuchyňka - PŘÍMÉ KURZY - NEBULA",
      track_color: "#7cfc00",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502620,
      name: "David",
      start_number: 12,
      description: "Radek David - CERES",
      track_color: "#a3a350",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502621,
      name: "Korbel",
      start_number: 13,
      description: "Evžen Korbel - MILKY WAY",
      track_color: "#cc10a3",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502622,
      name: "Horák",
      start_number: 14,
      description: "Pavel Horák - Kunratický Go & Yacht Club - METIS",
      track_color: "#ff7f0e",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502623,
      name: "Zvěřina",
      start_number: 15,
      description: "Martin Zvěřina - KETU",
      track_color: "#c5b0d5",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502624,
      name: "Gattermayer",
      start_number: 16,
      description: "Ondřej Gattermayer - CALISTO",
      track_color: "#008b8b",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502625,
      name: "Vejman",
      start_number: 17,
      description: "Lukáš Vejman - RHEA",
      track_color: "#1c676e",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502626,
      name: "Lowit",
      start_number: 18,
      description: "Harry Lowit - Yacht club Císařská louka - MONDO",
      track_color: "#8ba353",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502627,
      name: "Fedorik",
      start_number: 19,
      description: "Vladimir Fedorik - TRIMHO - MH82",
      track_color: "#ffd700",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502628,
      name: "Guryča",
      start_number: 20,
      description: "Daniel Guryča - MH47",
      track_color: "#3e1273",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502629,
      name: "Windisch",
      start_number: 21,
      description: "Martin Windisch - MH50",
      track_color: "#6d8a1c",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502630,
      name: "Slížek",
      start_number: 22,
      description: "Martin Slížek - Yacht Club Lipence - MH86",
      track_color: "#0050e9",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502631,
      name: "Kolín",
      start_number: 23,
      description: "Robert Kolín - HAVETS HOROR SAILING TEAM - SPECTRA",
      track_color: "#3d633e",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502632,
      name: "Faktor",
      start_number: 24,
      description: "Vlastimil Faktor - DIA",
      track_color: "#703329",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502633,
      name: "Pokorný",
      start_number: 25,
      description: "Jan Pokorný - MH55",
      track_color: "#FFFFFF",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502634,
      name: "Kupka",
      start_number: 26,
      description: "Petr Kupka  - Lirica crew - MH47",
      track_color: "#024d02",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502635,
      name: "Pavlíček",
      start_number: 27,
      description: "Zdeněk Pavlíček - PLEIADES",
      track_color: "#678cab",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502636,
      name: "Konupčík",
      start_number: 28,
      description: "Michal Konupčík - SK Halza - MH85",
      track_color: "#556071",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502637,
      name: "Štrobl",
      start_number: 29,
      description: "Stanislav Štrobl - BLACK TOT SAILING - KORE",
      track_color: "#772e35",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502638,
      name: "Straka",
      start_number: 30,
      description: "Tomáš Straka - Doktor Bumbu - MH80",
      track_color: "#000000",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502639,
      name: "Bělehrad",
      start_number: 31,
      description: "Pavel Bělehrad - REDSIDE SAILING TEAM - MH56",
      track_color: "#522cab",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502640,
      name: "Vistr",
      start_number: 32,
      description: "Tomas Vistr - ALBEDO",
      track_color: "#348a36",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502641,
      name: "Jaroš",
      start_number: 33,
      description: "Roman Jaroš - MH84",
      track_color: "#e371e3",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502642,
      name: "Kutiš",
      start_number: 34,
      description: "Ladislav Kutiš - CHOV DAŇKŮ - JANUS",
      track_color: "#ffff00",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502643,
      name: "Neuwirth",
      start_number: 35,
      description: "Radim Neuwirth - ENGINE WIND sailing team - MH51",
      track_color: "#bcffa8",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502644,
      name: "Piskacis",
      start_number: 36,
      description: "Ladislav Piskacis - MH78",
      track_color: "#bfa654",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502645,
      name: "Pospíšil",
      start_number: 37,
      description: "Martin Pospíšil - Jachtklub Brno - ELARA",
      track_color: "#ab57ab",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
      highlight: true,
    },
    {
      id: 201502646,
      name: "Hrubý",
      start_number: 38,
      description: "Erik Hrubý - MH81",
      track_color: "#308575",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502647,
      name: "Froněk",
      start_number: 39,
      description: "Petr Froněk - MH83",
      track_color: "#8fc165",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502648,
      name: "Melzer",
      start_number: 40,
      description: "Tomáš Melzer - SUDEŤÁCI - IO",
      track_color: "#2faf5f",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: true,
    },
    {
      id: 201502649,
      name: "Lohnickij",
      start_number: 41,
      description: "Štěpán Lohnickij - ELOS Sailing Team - ARTA",
      track_color: "#123456",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: false,
    },
    {
      id: 201502650,
      name: "Erban",
      start_number: 42,
      description: "Zdeněk Erban - Elen sailing - TOPAZ",
      track_color: "#654321",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: false,
    },
    {
      id: 201502651,
      name: "Hirnšal",
      start_number: 43,
      description: "Jan Hirnšal - RAVA",
      track_color: "#FF9955",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: false,
      highlight: true,
    },
    {
      id: 201502652,
      name: "Šejba",
      start_number: 44,
      description: "Filip Šejba - YC Rolling Bottles - SESTRRICA",
      track_color: "#5599FF",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: false,
    },
    {
      id: 201502653,
      name: "Satková",
      start_number: 45,
      description: "Ivana Satková - ZAZU",
      track_color: "#FF1122",
      track_length: 10800,
      race_committee: false,
      foto: "",
      boat_data: false,
    },
    {
      id: 201502654,
      name: "VR1",
      start_number: 46,
      description: "VR1",
      track_color: "#000000",
      track_length: 300,
      race_committee: true,
      foto: "https://www.velikonocniregata.cz/Content/Images/Race/cc9f2eca386041c88bb56d116993e360.jpg",
      boat_data: false,
    },
    {
      id: 201502655,
      name: "VR2",
      start_number: 47,
      description: "VR2",
      track_color: "#000000",
      track_length: 300,
      race_committee: true,
      foto: "https://www.velikonocniregata.cz/Content/Images/Race/cc9f2eca386041c88bb56d116993e360.jpg",
      boat_data: false,
    },
    {
      id: 201502656,
      name: "VR3",
      start_number: 48,
      description: "VR3",
      track_color: "#000000",
      track_length: 300,
      race_committee: true,
      foto: "https://www.velikonocniregata.cz/Content/Images/Race/cc9f2eca386041c88bb56d116993e360.jpg",
      boat_data: false,
    },
  ],
  cc_event_leg: [
    {
      id: 20151285,
      name: "VR 2025 - Etapa 1",
      active: 1,
      start: "2025-03-30T10:00:00+02:00",
      end: "2025-03-31T18:35:00+02:00",
      race_type: "offshore",
    },
    {
      id: 20151286,
      name: "VR 2025 - Etapa 2",
      active: 1,
      start: "2025-04-02T07:00:00+02:00",
      end: "2025-04-05T12:00:00+02:00",
      race_type: "offshore",
    },
  ],
  banner_set_live: {
    banners: [
      {
        id: 60,
        time: null,
        link: "https://www.expresmenu.com/",
        img: "/media_root/banners/expresmenu.jpg",
        name: "VR Expres Menu",
      },
      {
        id: 2,
        time: null,
        link: "http://www.yachtservice.cz/",
        img: "/media_root/banners/yachtservice.png",
        name: "4 Straka yacht",
      },
      {
        id: 63,
        time: null,
        link: "https://www.besednirestaurace.cz/",
        img: "/media_root/banners/u_ritschelu_100x100px.jpg",
        name: "VR Besedni restaurace",
      },
      {
        id: 66,
        time: null,
        link: "https://joinly.live",
        img: "/media_root/banners/joinly-wide.png",
        name: "VR Joinly",
      },
      {
        id: 59,
        time: null,
        link: "https://unetickypivovar.cz/",
        img: "/media_root/banners/unetickypivovar.jpg",
        name: "VR Uneticky Pivovar",
      },
      {
        id: 65,
        time: null,
        link: "https://inveprodevelop.cz/",
        img: "/media_root/banners/invepro_300x75_2x_v1.jpg",
        name: "VR CHMEL Invepro",
      },
      {
        id: 50,
        time: null,
        link: "https://www.khdkelectronics.com/",
        img: "/media_root/banners/khdk.png",
        name: "KHDK",
      },
      {
        id: 43,
        time: null,
        link: "https://www.artmaster.com/",
        img: "/media_root/banners/artmaster-cb.png",
        name: "6 Art Master",
      },
      {
        id: 12,
        time: null,
        link: "http://www.ifp-publishing.cz",
        img: "/media_root/banners/ifp.jpg",
        name: "VR AKITA - IFP",
      },
      {
        id: 10,
        time: null,
        link: "http://www.cfix.cz",
        img: "/media_root/banners/cfix.jpg",
        name: "VR CFIX",
      },
      {
        id: 38,
        time: null,
        link: "http://www.lodninoviny.cz",
        img: "/media_root/banners/lodninoviny.jpg",
        name: "5 Lodní noviny",
      },
      {
        id: 9,
        time: null,
        link: "http://www.bandzone.cz",
        img: "/media_root/banners/bandzone.png",
        name: "3 Bandzone",
      },
      {
        id: 11,
        time: null,
        link: "http://www.hellyhansen.com",
        img: "/media_root/banners/hh.jpg",
        name: "VR AKITA - HH",
      },
      {
        id: 64,
        time: null,
        link: "https://www.bytymlade.eu/",
        img: "/media_root/banners/mlade_300x75_2x_v2.jpg",
        name: "VR CHMEL Byty Mladé",
      },
      {
        id: 7,
        time: null,
        link: "http://www.yacht-magazine.cz",
        img: "/media_root/banners/Yacht_logo_nov%C3%A9.JPG",
        name: "Yacht Magazine",
      },
      {
        id: 3,
        time: null,
        link: "http://www.adc.cz/",
        img: "/media_root/banners/adc.jpg",
        name: "1 ADC",
      },
      {
        id: 1,
        time: null,
        link: "http://www.adcnet.cz/",
        img: "/media_root/banners/adcnet.png",
        name: "2 ADCnet.cz",
      },
    ],
  },
  banner_set_replay: {
    banners: [
      {
        id: 63,
        time: null,
        link: "https://www.besednirestaurace.cz/",
        img: "/media_root/banners/u_ritschelu_100x100px.jpg",
        name: "VR Besedni restaurace",
      },
      {
        id: 2,
        time: null,
        link: "http://www.yachtservice.cz/",
        img: "/media_root/banners/yachtservice.png",
        name: "4 Straka yacht",
      },
      {
        id: 65,
        time: null,
        link: "https://inveprodevelop.cz/",
        img: "/media_root/banners/invepro_300x75_2x_v1.jpg",
        name: "VR CHMEL Invepro",
      },
      {
        id: 3,
        time: null,
        link: "http://www.adc.cz/",
        img: "/media_root/banners/adc.jpg",
        name: "1 ADC",
      },
      {
        id: 38,
        time: null,
        link: "http://www.lodninoviny.cz",
        img: "/media_root/banners/lodninoviny.jpg",
        name: "5 Lodní noviny",
      },
      {
        id: 9,
        time: null,
        link: "http://www.bandzone.cz",
        img: "/media_root/banners/bandzone.png",
        name: "3 Bandzone",
      },
      {
        id: 7,
        time: null,
        link: "http://www.yacht-magazine.cz",
        img: "/media_root/banners/Yacht_logo_nov%C3%A9.JPG",
        name: "Yacht Magazine",
      },
      {
        id: 12,
        time: null,
        link: "http://www.ifp-publishing.cz",
        img: "/media_root/banners/ifp.jpg",
        name: "VR AKITA - IFP",
      },
      {
        id: 64,
        time: null,
        link: "https://www.bytymlade.eu/",
        img: "/media_root/banners/mlade_300x75_2x_v2.jpg",
        name: "VR CHMEL Byty Mladé",
      },
      {
        id: 11,
        time: null,
        link: "http://www.hellyhansen.com",
        img: "/media_root/banners/hh.jpg",
        name: "VR AKITA - HH",
      },
      {
        id: 59,
        time: null,
        link: "https://unetickypivovar.cz/",
        img: "/media_root/banners/unetickypivovar.jpg",
        name: "VR Uneticky Pivovar",
      },
      {
        id: 66,
        time: null,
        link: "https://joinly.live",
        img: "/media_root/banners/joinly-wide.png",
        name: "VR Joinly",
      },
      {
        id: 43,
        time: null,
        link: "https://www.artmaster.com/",
        img: "/media_root/banners/artmaster-cb.png",
        name: "6 Art Master",
      },
      {
        id: 1,
        time: null,
        link: "http://www.adcnet.cz/",
        img: "/media_root/banners/adcnet.png",
        name: "2 ADCnet.cz",
      },
      {
        id: 10,
        time: null,
        link: "http://www.cfix.cz",
        img: "/media_root/banners/cfix.jpg",
        name: "VR CFIX",
      },
      {
        id: 60,
        time: null,
        link: "https://www.expresmenu.com/",
        img: "/media_root/banners/expresmenu.jpg",
        name: "VR Expres Menu",
      },
      {
        id: 50,
        time: null,
        link: "https://www.khdkelectronics.com/",
        img: "/media_root/banners/khdk.png",
        name: "KHDK",
      },
    ],
  },
  boat_data_off: false,
};
